### ISSUE TITLE
Hangs on external executable call from pwsh on Linux

### ISSUE THREAD

**Issue by FeodorFitsner** [nickvdyck/webtty#140]
Hi Nick,

Thanks again for the great library! I'm looking into WebTty to replace our current PTY simulator implementation in AppVeyor Build Agent for Linux (currently it's a simple Python script calling `openpty`, but having everything in .NET is so appealing 😄). For proof-of-concept I did a simple .NET Core console project referencing `WebPty.Exec`. In that project I'm starting a new `Process` and asynchronously reading its output: https://github.com/FeodorFitsner/webtty/commit/b8a980ac2cdcef17c5ff7cb2a9af9f5bc4fa06b3#diff-a9e0b7c44edc8be222e6a7cefc795733 - nothing fancy, the simplest case.

When using `bash` as a host process - all is fine, everything works as expected: https://github.com/FeodorFitsner/webtty/commit/b8a980ac2cdcef17c5ff7cb2a9af9f5bc4fa06b3#diff-a9e0b7c44edc8be222e6a7cefc795733R23

However, when I use `pwsh` it's getting stuck on calls from PS session to any external process, such as `git`, `bash --version`, `ls`, etc.: https://github.com/FeodorFitsner/webtty/commit/b8a980ac2cdcef17c5ff7cb2a9af9f5bc4fa06b3#diff-a9e0b7c44edc8be222e6a7cefc795733R26. Regular PS cmdlets work, so it's not like completely dead.

I'm running the test app from WSL (Ubuntu 18.04) with:

```bash
appveyor@my-desktop:/mnt/c/Projects/Samples/webtty$ dotnet run --project src/WebTty.Examples/WebTty.Examples.csproj
```

It outputs `<ESC>[?1h=<ESC>[6n` and hangs.

What's interesting is that running `webtty` in WSL, going to http://127.0.0.1:500 and running the same `pwsh -command "ls --color=auto"` command works as expected.

What could be a problem with `pwsh`? Where to dig for the solution? Is it something with parent process (Kestrel, console app, threading model)? I hope you can advice. Thank you!

**Comment by nickvdyck** [comment]
Hi,

Thanks for this super detailed bug report and for providing those examples. 🙌 

I'm not sure what you mean with `hangs` though? Do you mean the program gets stuck and never exits or do you mean it's stuck for a couple of seconds and then prints out the rest of the output?

I just ran your examples on my mac and I can confirm I'm also experiencing some issue running `pwsh`. On my mac I get a similar result, it prints `[?1h=[6n[6n` then hangs for roughly 20 seconds after which it prints the rest of the output. 

I changed the command args slightly to  `new string[] { "-command", "Get-Date; ls --color=auto; Get-Date"` and  added a few `Console.WriteLine`s:

```sh
Start time: 10:54:57 PM
[?1h=
Thursday, April 16, 2020 10:54:58 PM
[6n[6n[0m[00;38;5;244m[m[00;38;5;245mCHANGELOG.md[0m           [00;38;5;244mLICENSE[0m    [00;38;5;244m[m[00;38;5;33massets[0m              [00;38;5;244m[m[00;38;5;245msetup.ps1[0m  [00;38;5;244mwebtty.sln[0m
[00;38;5;244mCommon.props[0m           [00;38;5;244m[m[00;38;5;245mMakefile[0m   [00;38;5;244m[m[00;38;5;33mdata[0m                [00;38;5;244m[m[00;38;5;33msrc[0m
[00;38;5;244mDirectory.Build.props[0m  [00;38;5;244m[m[00;38;5;245mREADME.md[0m  [00;38;5;244m[m[00;38;5;245mdocker-compose.yml[0m  [00;38;5;244m[m[00;38;5;33mtest[0m
[00;38;5;244m[m[00;38;5;245mDockerfile[0m             [00;38;5;244m[m[00;38;5;33martifacts[0m  [00;38;5;244m[m[00;38;5;33mdocs[0m                [00;38;5;244m[m[00;38;5;33mtools[0m
[?1h=]0;Thursday, April 16, 2020 10:55:18 PM

End time: 10:55:18 PM
```

I find it curious that for me it always hangs for exactly 20seconds, which I can't replicate when running via `webtty`. If it would hang completely and never return there probably is a deadlock which we don't get when running via asp.net due to different threading model. At the moment I'm completely baffled as to why this is happening. I can also only replicate this when running a command that runs as a separate process (ls, git, ..) PowerShell cmdlets run nice and snappy.

I would love to blame `pwsh` here, but that would be too easy 😂 . I have tested my implementation with a couple of tools and runtimes, but never with pwsh on Unix. I think I'll have to dust off my Windows PC and setup WSL again. I'll see if I can find some time to get that machine back up and running and will do some debugging with a similar setup this evening.

**Comment by FeodorFitsner** [comment]
Thanks for looking into that!

That's an interesting problem, indeed! 😄 I'm currently testing on Mac and seeing the same exact 20 seconds delay (and notice some garbage before `ls` output):

```
Thursday, April 16, 2020 2:35:21 PM
^[[44;1R^[[44;9Rosx-x64                    pty.runtimeconfig.json
pty.deps.json              test.ps1
pty.dll                    test.sh
pty.runtimeconfig.dev.json test2.ps1
Thursday, April 16, 2020 2:35:41 PM
```

```
Thursday, April 16, 2020 2:35:52 PM
^[[44;1R^[[44;9Rosx-x64                    pty.runtimeconfig.json
pty.deps.json              test.ps1
pty.dll                    test.sh
pty.runtimeconfig.dev.json test2.ps1
Thursday, April 16, 2020 2:36:12 PM
```

While running in WSL (Ubuntu 18.04) causes indefinite hang (you can change issue title). But, running on a real Linux VM (e.g. DigitalOcean) gives the same ~20 seconds delay.

Yes, running the same code via `webtty` works like a charm.

It "could" be `pwsh` as calling external program from bash host works without any delays. So, you are saying "asp.net due to different threading model" - is there any way to easily simulate that? Would creating a console Web App hosting Kestrel and registering the test as a worker service be enough? Or you are instantiating the `Process` on the first request?...

Btw, should I file an issue in PowerShell repo?

**Comment by FeodorFitsner** [comment]
OK, here's more food for the brain. Below is a simple Python script running in PTY the same `Get-Date; ls -G; Get-Date` in `pwsh`:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import errno
import os
import pty
import sys
import subprocess
import termios
import struct
import fcntl

def set_winsize(fd, row, col, xpix=0, ypix=0):
    winsize = struct.pack("HHHH", row, col, xpix, ypix)
    fcntl.ioctl(fd, termios.TIOCSWINSZ, winsize)

pty_width = 80
pty_height = 40
args = ['/usr/bin/pwsh', '-command', 'Get-Date; ls -G; Get-Date']

# open terminal and set its window size
out_r, out_w = pty.openpty()
set_winsize(out_w, pty_height, pty_width)

# spawn child process and redirect output to PTY
proc = subprocess.Popen(args, bufsize=0, stdout=out_w, stderr=out_w)
os.close(out_w) # if we do not write to process, close this.

while True:
    try:
        output = os.read(out_r, 100000).decode("utf-8")
        sys.stdout.write(output.encode("utf-8"))
    except OSError as e:
        if e.errno != errno.EIO: raise
        output = ""
    if not output:
		sys.exit(proc.wait())
```

Save it as `pty-run.py`. If you are running on macOS replace path to pwsh with `/usr/local/bin/pwsh`.

It's a Python 2.x script, doesn't work in 3.x. Run it with `-u` (unbuffered) option:

    python -u pty-run.py

Works without any delays on both macOS and WSL. Thoughts?

**Comment by nickvdyck** [comment]
Thanks for the script, I was just trying to write something together myself this saves me quite some time 👍 . Also when you set `UseTty` to false (then it just uses pipes) the process just runs normally without any delay or issues. So this is definitely an issue in my pty code, not sure where yet 🤔 .

I'm going to do a bit more sleuthing tomorrow, and dive through some python source code. 

Thanks for the help 🙌

**Comment by FeodorFitsner** [comment]
In the meantime I've created a simple Golang program running `pwsh` in PTY and (amazingly!) got the same mystical 20 seconds delay.

The program:

```golang
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"sync"

	"github.com/creack/pty"
)

func copyAndCapture(w io.Writer, r io.Reader) error {
	buf := make([]byte, 1024, 1024)
	for {
		n, err := r.Read(buf[:])
		if n > 0 {
			d := buf[:n]
			_, err := w.Write(d)
			if err != nil {
				return err
			}
		}
		if err != nil {
			// Read returns io.EOF at the end of file, which is not an error for us
			if err == io.EOF {
				err = nil
			}
			return err
		}
	}
}

func main() {
	cmd := exec.Command("/usr/local/bin/pwsh", "-command", "Get-Date;ls -G;Get-Date")

	f, err := pty.Start(cmd)
	if err != nil {
		panic(err)
	}

	var errStdout error
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		errStdout = copyAndCapture(os.Stdout, f)
		wg.Done()
	}()
	wg.Wait()

	err = cmd.Wait()
	if err != nil {
		fmt.Printf("Exited with %d\n", cmd.ProcessState.ExitCode())
	}
	if errStdout != nil {
		log.Fatal("failed to capture stdout or stderr\n")
	}
}
```

Execution results:

```
Friday, April 17, 2020 12:41:39 PM
^[[15;1R^[[15;9Ra.txt    main     main.go  test.ps1 test.sh
Friday, April 17, 2020 12:41:59 PM
```

Obviously, your code is using the same native PTY APIs that the most of other implementations. I guess trying to do the same in a Node.js app will yield the same results

The question still remains though why it's working in Python script and `webtty` web app, but not in a regular console app.

Let me know if you have any ideas.

**Comment by nickvdyck** [comment]
Nice sleuthing, thanks for that. I was digging a bit more into how python solves this problem. I wrote this script using `ptyprocess`,  a python module that allows running a process with a pty in a similar fashing as I do:

```python
import tty
import sys
import io

from ptyprocess import PtyProcess

from timeit import default_timer as timer


proc = PtyProcess.spawn(["pwsh", "-command", "Get-Date; ls --color=auto; Get-Date; stty -a; tty"], cwd="/Users/nickvd/Projects/webtty")

mode = tty.tcgetattr(proc.fileno())
print(mode)

stdout = io.open(proc.fd, 'rb', 0)

while proc.isalive():
    try:
        start = timer()
        result = stdout.read(1024)
        print("Read took {}s".format(timer() - start))
    except:
        pass

    sys.stdout.write(result.decode("utf-8"))
    sys.stdout.flush()

print("finished")
```

It has the exact same problem as my code and your golang example has. Which leads me to believe that python's subprocess module must be doing something extra to make it work.

I added a bit of profiling around the read api call. Both my C# implementation and the python example with `ptyprocess` has 2 read calls that hang each for 10s. But I have no clue as to why. 😕

So I tried getting some more information with `stty` and `tty`. `stty` can log and change current terminal pty settings and `tty` logs the file path of the current pty. Which gives me the following output running it from the python script with `subprocess`:

```sh
Slave: /dev/ttys002

Friday, April 17, 2020 10:36:38 PM
CHANGELOG.md	       LICENSE	  assets	      examples	 test
Common.props	       Makefile   data		      log.txt	 tools
Directory.Build.props  README.md  docker-compose.yml  setup.ps1  webtty.sln
Dockerfile	       artifacts  docs		      src
Friday, April 17, 2020 10:36:38 PM
speed 38400 baud; rows 38; columns 200;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; start = ^Q; stop = ^S; susp = ^Z; dsusp = ^Y; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; status = ^T; min = 1; time = 0;
-parenb -parodd cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
ixany imaxbel iutf8
opost -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -tostop -echoprt echoctl
echoke -flusho -extproc
/dev/ttys001
```

The tty settings are completely different from what you get from a vanilla `openpty`. Also, the tty path is completely different. So I'm guessing python somehow detects that stdout is a tty and creates it's own and configures it differently. It also seems it puts the pty in raw mode (I don't understand why), which is why you are not seeing any ansi color codes coming across.

At the moment I'm completely at a loss, I'm going to dig a bit more in python and maybe even golang source code and issues.

Let me know if you have any ideas on what else we could try. Running a bit thin on ideas here 😞

**Comment by FeodorFitsner** [comment]
I just leave it here. Node.js implementation doesn't work as well:

```node
var os = require('os');
var pty = require('node-pty');

var ptyProcess = pty.spawn('pwsh', ['-command', 'Get-Date; ls --color=auto; Get-Date'], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  process.stdout.write(data);
});

process.on('exit', () => ptyProcess.kill());

setTimeout(() => process.exit(), 30000);
```

Maybe there is something to do with `tcsetattr` to change TTY settings to "correct" one?...

`subprocess.Popen` in Python uses [`posix_spawn()`](https://github.com/python/cpython/blob/87502ddd710eb1f030b8ff5a60b05becea3f474f/Lib/subprocess.py#L1707) which is basically [`fork()` + `exec()`](http://man7.org/linux/man-pages/man3/posix_spawn.3.html) - doesn't look like it's an issue.

**Comment by FeodorFitsner** [comment]
If we look close at the output when it's stuck:
- in my original post it's one `^[6n` ([Query Cursor Position](http://www.termsys.demon.co.uk/vtansi.htm)) and hang
- in your second post it's double `^[6n^[6n` (10 seconds each?)
- in my 3rd post there is double `^[[44;1R^[[44;9R` ([Report Cursor Position](http://www.termsys.demon.co.uk/vtansi.htm)) which looked legitimate
- then golang execution results we see double `^[[15;1R^[[15;9R` again.
- running my last Node.js example in WSL gives a single `^[[26;1R` (report cursor position) and hangs.

It's all about cursor position. Could be a clue.

**Comment by FeodorFitsner** [comment]
This reference is better: https://vt100.net/docs/vt100-ug/chapter3.html#CPR

**Comment by nickvdyck** [comment]
I wrote a bit of code to validate if changing the TTY settings would have any effect. Changed the tty to the exact same settings as what python uses, but the programs still hangs. So that is definitely a dead end and doesn't seem to be the cause. 

It might be that `posix_spawn` is the magic juice here, although I still don't understand why it works when running `webtty`. It's also not the easiest API to port over to C# (without writing C or C++) so am not going to spend too much time on that yet. 

I think you are on the right track here, so I added some more profiling around my read API call. This is the result:

```sh
---------
Duration: 0ms
Read 37 characters.
Output in hex:
53617475726461792c20417072696c2031382c203230323020343a33393a313320504d0d0a

Output

Saturday, April 18, 2020 4:39:13 PM

---------
Duration: 11ms
Read 4 characters.
Output in hex:
1b5b366e

Output

^[[35;1R
---------
Duration: 10001ms
Read 4 characters.
Output in hex:
1b5b366e

Output

^[[35;1R
---------
Duration: 10014ms
Read 20 characters.
Output in hex:
6769742076657273696f6e20322e32362e310d0a

Output

git version 2.26.1

---------
Duration: 1ms
Read 7 characters.
Output in hex:
1b5b3f31681b3d

Output

```

As you can see it blocks the first time on reading `^[[35;1R` but the seconds time it's the output from `git`. So it seems that it blocks reading after each report cursor position VT sequence.  So it definitely looks like you are on the right track here. 😄 

Just to recap:

- We have been able to replicate this behaviour with 4 (actually 5 libraries if I count `ptyprocess`) different frameworks and languages (C#, golang, python, node)
- We can only replicate with `pws`, I tried all the shells or repls that I have on my machine (csh, zsh, bash, node, python, ...). All of them work just fine.
- It seems to be hanging after `Query Cursor Position` or `Report Cursor Position` VT sequences.

So I'm out of ideas at this point. Maybe now is the time to file an issue to PowerShell and hope they don't mind/ have time or resources to look into it. 

WDYT?

**Comment by FeodorFitsner** [comment]
I've been playing a lot with `webtty`, creating `Process` here and reading output there - it's always working when output is read in a websocket response thread. All other cases lead to the magic `^[6n` hang/delay.

But suddenly it clicked "OK, if you are asking for cursor position let's provide you that information!".

I've figured out a "workaround" for C# implementation. The idea is sending fake cursor position to slave (stdin) whenever master (stdout) is asking for it:

```csharp
const int maxReadSize = 1024;
var buffer = new byte[maxReadSize];

while (terminal.IsRunning)
{
	try
	{
		var read = await stream.ReadAsync(buffer, 0, maxReadSize);
                if (read == 0)
                {
                    break;
                }

		var ds = Encoding.UTF8.GetString(buffer, 0, read);

		if (ds == "\u001b[6n")
		{
			terminal.Stdin.BaseStream.Write(Encoding.UTF8.GetBytes("\u001b[[1;1R"));
			await terminal.Stdin.FlushAsync();
		}

		Console.Write(ds.Replace("\u001b", ""));
		await Console.Out.FlushAsync();
	}
	catch
	{
		break;
	}
}
```

The "solution" works for both WSL and macOS. Could you please verify on your side?

Of course, questions remain a) why it's not asking for cursor position in ASP.NET context, b) is there any way to "tell" slave it doesn't support asking for cursor position or c) why `pwsh` sees terminals differently.

**Comment by nickvdyck** [comment]
Oh nice, this is genius. 🙌 .

I haven't been able to run the example yet, but I know why this is the solution:

a: It is asking for cursor position in ASP.NET, I just don't need to do anything special for because of xterm.js handeling this for me. You can see it in the console, it's in binary but you see it sending an input request:

```
N°SendInputRequest¥TabIdÙ$83a4141c-00eb-4d90-b76a-06e4d0a51c3a§Payload¦[3;1R
```

It sends `[3;1R` because I first ran `Get-Date` and after that `ls`

b: I'm not sure yet if you can turn this off, but I guess that's what python is doing.

c: I don't think `pwsh` sees terminals differently. I bet you they have code somewhere where they detect a pty and then run this to figure out where to write the output of an external process. The just time out after 10 seconds try again and probably after 2 tries give up.

**Comment by nickvdyck** [comment]
When I say in the console. I mean that in the browser network tab you can observe all data travelling over the web socket.

**Comment by nickvdyck** [comment]
Oh, now it totally clicks for me. I know what python is doing because I mentioned it above. It puts the tty in raw mode. And it probably does that to prevent this exact scenario. 

I can add a another process property to control the tty mode and put in raw mode. Will nedd code similar like this: https://github.com/python/cpython/blob/482259d0dcf27714a84cf56b93977320bea7e093/Lib/tty.py#L18

**Comment by FeodorFitsner** [comment]
Fantastic! 😄 When would you have a chance to add that? I can't wait to test it in production! 😄

**Comment by nickvdyck** [comment]
Oh, I was so wrong earlier, should have tested my hypotheses first. 🤦 . This issue had nothing to do with tty modes. I played with so many things in my terminal I probably put it in raw mode myself. Running the `tty` command from python's subprocess just reflected my terminals tty settings right back at me. Because `tty` prints the file name of the terminal connected to standard input (http://man7.org/linux/man-pages/man1/tty.1.html) and thus `stty` gives you the settings for that same tty.

What python actually does is way simpler. If you don't provide a file descriptor for stdin, it just won't connect it up. Which means it will inherit stdin from its parent process. In python if you would do this:

```python
proc = subprocess.Popen(args, bufsize=1, stdin=slave_fd,stdout=slave_fd, stderr=slave_fd)
```

You will get the exact same issue we saw in other languages. Because at that point you will need to handle any vt escape sequence yourself (like you demonstrated in your example). When I implemented this initially I followed the go and ptexpect implementation, where you have a single `usetty` flag and `stdin`, `stdout` and `stderr` will get connected to its slave. The reason I implemented it this way is that I didn't think it was possible to have stdin be connected to a different tty than stdout.

So to fix it I'm going to change the behaviour to only connect when specifically asked to redirect stdin, stdout or stderr. This is also how it works in dotnet (albeit not with tty's): https://github.com/dotnet/runtime/blob/b88be15f5cca9d4a04980974bedea63e12af06e1/src/libraries/Native/Unix/System.Native/pal_process.c#L379

Sr for the long explanation, I just wanted it written down so I can come back to it again if I ever need to 🙈 .

Thanks for helping debug this issue, I would have never figured it out otherwise. 🙌  😄  I will try to push up a commit today with a fix.

**Comment by FeodorFitsner** [comment]
That totally makes sense! Thanks for your efforts - will test it as soon as commit's ready.

As a side note. It would be cool if you release `WebTty.Exec` as a standalone NuGet package. Personally, I see a great value in a solid .NET Core PTY bindings for Windows, Linux and Mac.

**Comment by nickvdyck** [comment]
I pushed up a fix in this commit  a7bc7be. I haven't tested it yet on Linux, but I assume it should just work. 🙃 

I agree it could definitely be useful as a separate library. I have some other personal projects in mind that I can use this for. Until now I have always held it off. But I created this #142 for me personally to track progress. I'm planning to spend some time on that this week and get it done. You could just keep an eye on that issue if you would like to track progress 😄 . I would love to give it a different name an am going to think about that for a couple of days.

Anyways thanks a lot for all your help 🙌  😄

**Comment by FeodorFitsner** [comment]
Cool, thank you! I'm going to try it out and let you know!

**Comment by FeodorFitsner** [comment]
Could you share your test please? Looks like it doesn't work on both WSL and Mac. Maybe I'm doing something wrong...

**Comment by nickvdyck** [comment]
I added my example to this branch `pty-tests`, I think the only line I have different from yours is this one: https://github.com/nickvdyck/webtty/blob/7f32cf7be13e84b928321703e4c627990ae85fb6/src/WebTty.Example/Program.cs#L64

**Comment by nickvdyck** [comment]
🤦 Now I understand how it works in python. The python scripts echo everything back to the parent tty (tty in your terminal). If you would remove writing to stdout from the python script you would see that it will hang.

I'm not sure how the actual script is working in your setup. But I think you will need to echo everything back to the parent tty to not have it hang for pwsh scripts.

**Comment by FeodorFitsner** [comment]
I'm almost lost here :) How would you do that in my example?

**Comment by nickvdyck** [comment]
Yeah sr, it's difficult to explain. But stop stripping out `\u001b` on this line:
https://github.com/FeodorFitsner/webtty/commit/b8a980ac2cdcef17c5ff7cb2a9af9f5bc4fa06b3#diff-a9e0b7c44edc8be222e6a7cefc795733R46
. Then it should start to work.

**Comment by FeodorFitsner** [comment]
Oh, snap! Indeed. 😄 Seems I know why it was working with Python script.

With Python script a call structure was looking like:

```
agent
  |
  +-- python -u pty-util.py
               |
               +-- /usr/bin/pwsh
```

agent was just reading the output from a Python script and python script was writing to stdout.

Now when I'm trying to use PTY natively it looks like:

```
agent
  |
  +-- /usr/bin/pwsh
```

**Comment by FeodorFitsner** [comment]
I'm going to play with the lib on a real app and see how it goes in WSL and VMs. Thank you for bearing with me!

**Comment by FeodorFitsner** [comment]
Is it just me or setting the size of Unix PTY doesn't work? For example, running console test with default 80 x 24 and generating a very long line is not wrapped into lines:

```posh
for($i = 0; $i -lt 2000; $i++) {
  Write-Host "." -NoNewline
}
```

Could you please check?

**Comment by nickvdyck** [comment]
Ah yes sr about that, this library hasn't been truly tested for anything but what I use it for in `webtty`. I created an issue for this: #143, feel free to make PR for it. Otherwise, I'll just pick it up tomorrow. 😄 

Also to be fair the example you give here is probably not going to work. You need a program that checks if it is running on a tty and then gets the tty size. For example `ls` does this and then will print out more or fewer columns. I don't think Write-Host is aware of this.

**Comment by FeodorFitsner** [comment]
You were right! `ls` respects the width of virtual screen, `pwsh` doesn't.
